[".local/share/antidote"]
  type = "git-repo"
  urL = "https://github.com/mattmc3/antidote.git"
  refreshPeriod = "168h"  # Refresh once a week

[".local/share/doom-emacs"]
  type = "git-repo"
  url = "https://github.com/hlissner/doom-emacs"
  refreshPeriod = "168h"

[".local/share/spacemacs"]
  type = "git-repo"
  url = "https://github.com/syl20bnr/spacemacs"
  refreshPeriod = "168h"

[".local/share/chemacs"]
  type = "git-repo"
  url = "https://github.com/plexus/chemacs"
  refreshPeriod = "168h"

# ln -sf "${APPDIR}/chemacs/.emacs" "${HOME}/.emacs"

# ["{{ .chezmoi.homeDir }}/Applications/brew"]
#   type = "archive"
#   url = "https://github.com/homebrew/brew/tarball/master"
#   exact = true
#   stripComponents = 1
#   format = "xz"
# {{- if eq .chezmoi.os "linux" }}
# ["{{ .chezmoi.homeDir }}/Applications/miniconda"]
#   type = "file"
#   url = "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
#   executable = true
# {{- end -}}
# #!/usr/bin/env bash
# 
# source /.profile
# 
# {{- if eq .chezmoi.os "darwin" }}
# # Updating to install MiniForge, instead of Miniconda
# echo "- Installing MiniForge..."
# brew install miniforge
# 
# {{- else if eq .chezmoi.os "linux" }}
# 
# #: Setting up Miniconda
# echo "- Installing Miniconda..."
# url="https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
# quiet "curl -fsSL -o ${HOME}/miniconda.sh ${url}"
# chmod +x "${HOME}/miniconda.sh"
# bash ${HOME}/miniconda.sh -b -p {{ .appDir }}/miniconda
# rm "${HOME}/miniconda.sh"
# {{ end -}}
# 
# conda install -c conda-forge mamba --yes
# 
# echo "- Update conda \`base\` environment..."
# source dot_profile
# 
# quiet "mamba env update -n base -f {{ .chezmoi.sourceDir }}/@setup/env.yml"
