#!/usr/bin/env bash
#: #############################################################################
#: @jmuchovej/.bashrc
#: Thanks for taking a look at my dotfiles! :blush:
#: However, it's definitely necessary to cite my sources, which made building
#:   this so much easier. :sweat_smile:
#:   - https://carlosbecker.com/posts/speeding-up-zsh/
#:   - https://blog.callstack.io/supercharge-your-terminal-with-zsh-8b369d689770
#: #############################################################################
[ -f $HOME/.profile ] && source $HOME/.profile

[ $(command -v module) ] && module load $(load-modules)

#: font to be used: "Fira Code", https://github.com/tonsky/FiraCode/releases
conda activate base

#: source all the things
for file in $(ls ${XDG_CONFIG_HOME}/bash/??-*.bash); do
    source $file
done

source ${XDG_CONFIG_HOME}/bash/@$(uname).bash

#: prompt configuration
eval "$(starship init bash)"

#: setup additional hooks and whatnot
# [ $(which direnv) ] && eval "$(direnv hook bash)"

#: fuzzy-finder
[ $(which fzf) ] && source "$(brew --prefix)/opt/fzf/shell/key-bindings.bash"

to_source=()
# The next line updates PATH for Netlify's Git Credential Helper.
to_source+="${HOME}/.netlify/helper/path.bash.inc"
to_source+="${XDG_DATA_HOME}/funky/funky.sh"
for file in "${to_source[@]}"; do
    [ -f ${file} ] && source ${file}
done
unset to_source

iterm2="${HOME}/.iterm2_shell_integration.bash"
test -e "${iterm2}" && source "${iterm2}"
unset iterm2

set +v  # https://askubuntu.com/a/813946/585721
