#!/usr/bin/env zsh

source ~/.profile

#: Setup $PATH to be unique
typeset -U path

export ZSH="${XDG_CONFIG_HOME}/zsh"
# export ZSH="${ZDOTDIR}"

export PLUGINS="${ZSH}/plugins"

#: ZSH History Configuration
HISTFILE="${ZSH}/history"
HISTSIZE=100000
SAVEHIST="${HISTSIZE}"
ZSH_AUTOSUGGEST_STRATEGY="history"

export _Z_DATA="${XDG_DATA_HOME}/z/data"
[ -d $(dirname ${_Z_DATA}) ] || mkdir -p $(dirname ${_Z_DATA})
export _Z_OWNER=$(whoami)
