[".tmux.conf"]
  type = "file"
  url = "https://github.com/gpakosz/.tmux/raw/master/.tmux.conf"
  exact = true
  refreshPeriod = "168h"

[".local/src/z.sh"]
  type = "git-repo"
  url = "https://github.com/rupa/z"
  refreshPeriod = "168h"

[".local/opt/SpaceVim"]
  type = "git-repo"
  url = "https://github.com/SpaceVim/SpaceVim.git"
  refreshPeriod = "168h"

[".local/opt/brew"]
  type = "git-repo"
  url = "https://github.com/homebrew/brew.git"
  refreshPeriod = "24h"

[".local/opt/antidote"]
  type = "git-repo"
  url = "https://github.com/mattmc3/antidote.git"
  refreshPeriod = "168h"  # Refresh once a week

[".local/opt/doom-emacs"]
  type = "git-repo"
  url = "https://github.com/hlissner/doom-emacs.git"
  refreshPeriod = "168h"

[".local/opt/spacemacs"]
  type = "git-repo"
  url = "https://github.com/syl20bnr/spacemacs.git"
  refreshPeriod = "168h"

[".emacs.d"]
  type = "git-repo"
  url = "https://github.com/plexus/chemacs2.git"
  refreshPeriod = "168h"

{{- $starship_vendor_os := "" }}
{{- if eq .chezmoi.os "darwin" }}
  {{ $starship_vendor_os = "apple-darwin" }}
{{- else if eq .chezmoi.os "linux" }}
  {{ $starship_vendor_os = "unknown-linux-musl" }}
{{- end }}

[".local/bin/starship"]
  type = "file"
  url = "https://github.com/starship/starship/releases/latest/download/starship-{{ .alt.arch }}-{{ $starship_vendor_os }}.tar.gz" 
  executable = true
  refreshPeriod = "168h"
  [".local/bin/starship".filter]
    command = "tar"
    args = ["--extract", "--gzip", "--file", "/dev/stdin", "--to-stdout", "starship"]

[".local/bin/direnv"]
  type = "file"
  url = "https://github.com/direnv/direnv/releases/latest/download/direnv.{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
  executable = true
  refreshPeriod = "168h"

[".local/opt/asdf"]
  type = "git-repo"
  url = "https://github.com/asdf-vm/asdf.git"
  refreshPeriod = "168h"

# TODO: Figure out how to avoid putting RClone into `~/.local/bin` to ensure it's an unused key...
[".local/bin"]
  type = "archive"
  url = "https://downloads.rclone.org/rclone-current-{{ .alt.os }}-{{ .chezmoi.arch }}.zip"
  refreshPeriod = "168h"
  include = ["*/rclone"]
  stripComponents = 1

# Pulled from https://github.com/twpayne/dotfiles/blob/master/home/.chezmoiexternal.toml#L23-L37
{{- $ageVersion := "1.0.0" }}
[".local/bin/age"]
    type = "file"
    url = "https://github.com/FiloSottile/age/releases/download/v{{ $ageVersion }}/age-v{{ $ageVersion }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
    command = true
    [".local/bin/age".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "age/age"]
[".local/bin/age-keygen"]
    type = "file"
    url = "https://github.com/FiloSottile/age/releases/download/v{{ $ageVersion }}/age-v{{ $ageVersion }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
    command = true
    [".local/bin/age-keygen".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "age/age-keygen"]

