default_language_version:
  python: python3
repos:
- repo: "https://github.com/pre-commit/pre-commit-hooks"
  rev: "v4.6.0"
  hooks:
  - id: "trailing-whitespace"
  - id: "end-of-file-fixer"
  - id: "check-yaml"
  - id: "check-toml"
  - id: "detect-private-key"
  - id: "check-case-conflict"
  - id: "check-added-large-files"
    args: ["--maxkb=10000"]

- repo: "https://github.com/shellcheck-py/shellcheck-py"
  rev: "v0.9.0.2"
  hooks:
  - id: "shellcheck"

- repo: "https://github.com/compilerla/conventional-pre-commit"
  rev: "v3.4.0"
  hooks:
  - id: "conventional-pre-commit"
    stages: ["commit-msg"]
    args: [ "build", "chore", "docs", "feat", "fix", "perf", "refactor", "revert", "style", "test", ]
