#!/usr/bin/env zsh

export XDG_CONFIG_HOME="${HOME}/.config"
export ZSH="${XDG_CONFIG_HOME}/zsh"
export ZDOTDIR="${ZSH}"

export HISTFILE="${ZDOTDIR}/.history"
export HISTSIZE=100000
export SAVEHIST="${HISTSIZE}"
export ZSH_AUTOSUGGEST_STRATEGY="history"

[[ -f ${ZDOTDIR}/.zshenv ]] && source ${ZDOTDIR}/.zshenv

# source ~/.profile
# 
# #: Setup $PATH to be unique
# typeset -U path
# 
# 
# #: ZSH History Configuration
# HISTFILE="${ZSH}/history"
# HISTSIZE=100000
# SAVEHIST="${HISTSIZE}"
# ZSH_AUTOSUGGEST_STRATEGY="history"
# 
# export _Z_DATA="${XDG_DATA_HOME}/z/data"
# [ -d $(dirname ${_Z_DATA}) ] || mkdir -p $(dirname ${_Z_DATA})
# export _Z_OWNER=$(whoami)
# 
