#!/usr/bin/env bash
# TODO determine what "minimal" install would look like and enable
# TODO on MacOS; @Darwain/dock.bash needs to determine if Flotato exists

#: Fail fast
set -e

if [ ! "$(command -v chezmoi)" ]; then
  bin_dir="$HOME/.local/bin"
  chezmoi="${bin_dir}/chezmoi"
  if [ "$(command -v curl)" ]; then
    sh -c "$(curl -fsSL https://git.io/chezmoi)" -- -b "${bin_dir}"
  elif [ "$(command -v wget)" ]; then
    sh -c "$(wget -qO- https://git.io/chezmoi)" -- -b "${bin_dir}"
  else
    echo "To install \`chezmoi\`, you must have \`curl\` or \`wget\` installed." >&2
  fi
else
  chezmoi=chezmoi
fi

script_dir="$(cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P)"
exec "${chezmoi}" init --apply "--source=${script_dir}"
