#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  automatic_update = true
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "palenight"
  colorscheme_bg = "dark"
  guifont = "JetBrains Mono Nerd Font:h11"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "arrow"
  statusline_iseparator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false

  bootstrap_before = "custom#before"
  bootstrap_after  = "custom#after"

#: https://spacevim.org/layers/autocomplete/
[[layers]]
  name = "autocomplete"
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

#: https://spacevim.org/layers/shell/
[[layers]]
  name = "shell"
  default_position = "top"
  default_height = 30

#: https://spacevim.org/layers/colorscheme/
[[layers]]
  name = "colorscheme"

#: https://spacevim.org/layers/sudo/
[[layers]]
  name = "sudo"

#: https://spacevim.org/layers/git/
[[layers]]
  name = "git"

#: https://spacevim.org/layers/fzf/
[[layers]]
  name = "fzf"

#: https://spacevim.org/layers/lsp/
# [[layers]]
#   name = "lsp"
#   filetypes = [
#     "python", "julia", "vim",
#     "javascript", "javascript",
#   ]

#: https://spacevim.org/layers/lang/julia/
[[layers]]
  name = "lang#julia"

#: https://spacevim.org/layers/lang/python/
[[layers]]
  name = "lang#python"

#: https://spacevim.org/layers/lang/r/
[[layers]]
  name = "lang#r"

#: https://spacevim.org/layers/lang/typescript/
[[layers]]
  name = "lang#typescript"

#: https://spacevim.org/layers/org/
[[layers]]
  name = "org"

#: https://spacevim.org/layers/lang/markdown/
[[layers]]
  name = "lang#markdown"
  
[[custom_plugins]]
  repo = "https://github.com/alker0/chezmoi.vim.git"
  merged = false
